/// Centralized UI strings and translations dictionary for INPLAYER Android.
/// Supports English and 11 Scheduled Indian regional languages.
/// Provides fallback to English for any missing translation keys.
class AppStrings {
  final String code;

  // Navigation
  final String home;
  final String shorts;
  final String music;
  final String search;
  final String library;
  final String profile;
  final String settings;
  final String downloads;
  final String notifications;
  final String messages;
  final String channels;
  final String creatorStudio;
  final String mart;

  // Actions & Buttons
  final String play;
  final String pause;
  final String save;
  final String share;
  final String like;
  final String dislike;
  final String subscribe;
  final String subscribed;
  final String cancel;
  final String confirm;
  final String apply;
  final String edit;
  final String delete;
  final String report;
  final String skip;
  final String close;
  final String signIn;
  final String signOut;
  final String back;
  final String done;
  final String retry;

  // Menus & Dialogs
  final String quality;
  final String captions;
  final String captionsOff;
  final String speed;
  final String audioTrack;
  final String reportIssue;
  final String addToPlaylist;
  final String themeAppearance;
  final String chooseAppearance;

  // Settings & Legal
  final String settingsTitle;
  final String language;
  final String languageDesc;
  final String selectLanguage;
  final String appearance;
  final String playback;
  final String privacy;
  final String plans;
  final String analytics;
  final String storage;
  final String about;
  final String legalPolicies;
  final String termsOfService;
  final String privacyPolicy;
  final String childSafetyPolicy;
  final String communityGuidelines;

  // States
  final String loading;
  final String noResults;
  final String errorOccurred;
  final String offline;
  final String success;

  const AppStrings({
    required this.code,
    required this.home,
    required this.shorts,
    required this.music,
    required this.search,
    required this.library,
    required this.profile,
    required this.settings,
    required this.downloads,
    required this.notifications,
    required this.messages,
    required this.channels,
    required this.creatorStudio,
    required this.mart,
    required this.play,
    required this.pause,
    required this.save,
    required this.share,
    required this.like,
    required this.dislike,
    required this.subscribe,
    required this.subscribed,
    required this.cancel,
    required this.confirm,
    required this.apply,
    required this.edit,
    required this.delete,
    required this.report,
    required this.skip,
    required this.close,
    required this.signIn,
    required this.signOut,
    required this.back,
    required this.done,
    required this.retry,
    required this.quality,
    required this.captions,
    required this.captionsOff,
    required this.speed,
    required this.audioTrack,
    required this.reportIssue,
    required this.addToPlaylist,
    required this.themeAppearance,
    required this.chooseAppearance,
    required this.settingsTitle,
    required this.language,
    required this.languageDesc,
    required this.selectLanguage,
    required this.appearance,
    required this.playback,
    required this.privacy,
    required this.plans,
    required this.analytics,
    required this.storage,
    required this.about,
    required this.legalPolicies,
    required this.termsOfService,
    required this.privacyPolicy,
    required this.childSafetyPolicy,
    required this.communityGuidelines,
    required this.loading,
    required this.noResults,
    required this.errorOccurred,
    required this.offline,
    required this.success,
  });

  static const english = AppStrings(
    code: 'en',
    home: 'Home',
    shorts: 'Raftaar Shorts',
    music: 'Music',
    search: 'Search',
    library: 'Library',
    profile: 'Profile',
    settings: 'Settings',
    downloads: 'Downloads',
    notifications: 'Notifications',
    messages: 'Messages',
    channels: 'Channels',
    creatorStudio: 'Creator Studio',
    mart: 'Hammart',
    play: 'Play',
    pause: 'Pause',
    save: 'Save',
    share: 'Share',
    like: 'Like',
    dislike: 'Dislike',
    subscribe: 'Subscribe',
    subscribed: 'Subscribed',
    cancel: 'Cancel',
    confirm: 'Confirm',
    apply: 'Apply',
    edit: 'Edit',
    delete: 'Delete',
    report: 'Report',
    skip: 'Skip',
    close: 'Close',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    back: 'Back',
    done: 'Done',
    retry: 'Retry',
    quality: 'Quality',
    captions: 'Captions',
    captionsOff: 'Off',
    speed: 'Playback Speed',
    audioTrack: 'Audio Track',
    reportIssue: 'Report an issue',
    addToPlaylist: 'Add to playlist',
    themeAppearance: 'Theme & Appearance',
    chooseAppearance: 'Choose Appearance',
    settingsTitle: 'Settings',
    language: 'Language',
    languageDesc: 'Choose your preferred display language',
    selectLanguage: 'Select App Language',
    appearance: 'Appearance',
    playback: 'Playback',
    privacy: 'Account & Privacy',
    plans: 'Plans & Purchases',
    analytics: 'Analytics',
    storage: 'Storage',
    about: 'About InPlayer',
    legalPolicies: 'Legal & Policies',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    childSafetyPolicy: 'Child Safety Policy',
    communityGuidelines: 'Community Guidelines',
    loading: 'Loading...',
    noResults: 'No results found',
    errorOccurred: 'An error occurred',
    offline: 'You are offline',
    success: 'Success',
  );

  static const hindi = AppStrings(
    code: 'hi',
    home: 'होम',
    shorts: 'रफ्तार शॉर्ट्स',
    music: 'संगीत',
    search: 'खोजें',
    library: 'लाइब्रेरी',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    downloads: 'डाउनलोड्स',
    notifications: 'सूचनाएं',
    messages: 'संदेश',
    channels: 'चैनल्स',
    creatorStudio: 'क्रिएटर स्टूडियो',
    mart: 'हामार्ट',
    play: 'चलाएं',
    pause: 'रोकें',
    save: 'सहेजें',
    share: 'शेयर करें',
    like: 'पसंद',
    dislike: 'नापसंद',
    subscribe: 'सब्सक्राइब',
    subscribed: 'सब्सक्राइब किया',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    apply: 'लागू करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    report: 'रिपोर्ट करें',
    skip: 'छोड़ें',
    close: 'बंद करें',
    signIn: 'साइन इन करें',
    signOut: 'साइन आउट करें',
    back: 'पीछे',
    done: 'पूर्ण',
    retry: 'पुनः प्रयास करें',
    quality: 'गुणवत्ता',
    captions: 'उपशीर्षक / कैप्शन',
    captionsOff: 'बंद',
    speed: 'गति',
    audioTrack: 'ऑडियो ट्रैक',
    reportIssue: 'समस्या की रिपोर्ट करें',
    addToPlaylist: 'प्लेलिस्ट में जोड़ें',
    themeAppearance: 'थीम और दिखावट',
    chooseAppearance: 'दिखावट चुनें',
    settingsTitle: 'सेटिंग्स',
    language: 'भाषा',
    languageDesc: 'अपनी पसंदीदा भाषा चुनें',
    selectLanguage: 'ऐप की भाषा चुनें',
    appearance: 'दिखावट',
    playback: 'प्लेबैक',
    privacy: 'खाता और गोपनीयता',
    plans: 'प्लान और खरीदारी',
    analytics: 'एनालिटिक्स',
    storage: 'स्टोरेज',
    about: 'के बारे में',
    legalPolicies: 'कानूनी नीतियां',
    termsOfService: 'सेवा की शर्तें',
    privacyPolicy: 'गोपनीयता नीति',
    childSafetyPolicy: 'बाल सुरक्षा नीति',
    communityGuidelines: 'समुदाय दिशानिर्देश',
    loading: 'लोड हो रहा है...',
    noResults: 'कोई परिणाम नहीं मिला',
    errorOccurred: 'एक त्रुटि हुई',
    offline: 'आप ऑफ़लाइन हैं',
    success: 'सफल',
  );

  static const bengali = AppStrings(
    code: 'bn',
    home: 'হোম',
    shorts: 'রফতার শর্টস',
    music: 'সঙ্গীত',
    search: 'অনুসন্ধান',
    library: 'লাইব্রেরি',
    profile: 'প্রোফাইল',
    settings: 'সেটিংস',
    downloads: 'ডাউনলোড',
    notifications: 'বিজ্ঞপ্তি',
    messages: 'বার্তা',
    channels: 'চ্যানেল',
    creatorStudio: 'নির্মাতা স্টুডিও',
    mart: 'হামার্ট',
    play: 'চালান',
    pause: 'থামান',
    save: 'সংরক্ষণ',
    share: 'শেয়ার',
    like: 'পছন্দ',
    dislike: 'অপছন্দ',
    subscribe: 'সাবস্ক্রাইব',
    subscribed: 'সাবস্ক্রাইবড',
    cancel: 'বাতিল',
    confirm: 'নিশ্চিত করুন',
    apply: 'প্রয়োগ করুন',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    report: 'অভিযোগ',
    skip: 'এড়িয়ে যান',
    close: 'বন্ধ করুন',
    signIn: 'সাইন ইন',
    signOut: 'সাইন আউট',
    back: 'ফিরে যান',
    done: 'সম্পন্ন',
    retry: 'আবার চেষ্টা করুন',
    quality: 'গুণমান',
    captions: 'সাবটাইটেল / ক্যাপশন',
    captionsOff: 'বন্ধ',
    speed: 'গতি',
    audioTrack: 'অডিও ট্র্যাক',
    reportIssue: 'সমস্যা রিপোর্ট করুন',
    addToPlaylist: 'প্লেলিস্টে যোগ করুন',
    themeAppearance: 'চেহারা ও থিম',
    chooseAppearance: 'থিম বেছে নিন',
    settingsTitle: 'সেটিংস',
    language: 'ভাষা',
    languageDesc: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    selectLanguage: 'অ্যাপের ভাষা বেছে নিন',
    appearance: 'চেহারা',
    playback: 'প্লেব্যাক',
    privacy: 'অ্যাকাউন্ট ও গোপনীয়তা',
    plans: 'প্ল্যান ও ক্রয়',
    analytics: 'অ্যানালিটিক্স',
    storage: 'স্টোরেজ',
    about: 'ইনপ্লেয়ার সম্পর্কে',
    legalPolicies: 'আইনি নীতিসমূহ',
    termsOfService: 'ব্যবহারের শর্তাবলী',
    privacyPolicy: 'গোপনীয়তা নীতি',
    childSafetyPolicy: 'শিশু সুরক্ষা নীতি',
    communityGuidelines: 'কমিউনিটি নির্দেশিকা',
    loading: 'লোড হচ্ছে...',
    noResults: 'কোন ফলাফল পাওয়া যায়নি',
    errorOccurred: 'একটি ত্রুটি ঘটেছে',
    offline: 'আপনি অফলাইনে আছেন',
    success: 'সফল',
  );

  static const tamil = AppStrings(
    code: 'ta',
    home: 'முகப்பு',
    shorts: 'ரஃப்தார் ஷார்ட்ஸ்',
    music: 'இசை',
    search: 'தேடுக',
    library: 'நூலகம்',
    profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்',
    downloads: 'பதிவிறக்கங்கள்',
    notifications: 'அறிவிப்புகள்',
    messages: 'செய்திகள்',
    channels: 'சேனல்கள்',
    creatorStudio: 'படைப்பாளர் ஸ்டுடியோ',
    mart: 'ஹாமார்ட்',
    play: 'இயக்கு',
    pause: 'நிறுத்து',
    save: 'சேமி',
    share: 'பகிர்',
    like: 'விருப்பம்',
    dislike: 'வெறுப்பு',
    subscribe: 'சந்தா சேர்',
    subscribed: 'சந்தாதாரர்',
    cancel: 'ரத்து செய்',
    confirm: 'உறுதி செய்',
    apply: 'பயன்படுத்து',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    report: 'புகாரளி',
    skip: 'தவிர்',
    close: 'மூடு',
    signIn: 'உள்நுழைக',
    signOut: 'வெளியேறு',
    back: 'பின்செல்',
    done: 'முடிந்தது',
    retry: 'மீண்டும் முயற்சி செய்',
    quality: 'தரம்',
    captions: 'துணைத்தலைப்புகள்',
    captionsOff: 'ஆஃப்',
    speed: 'வேகம்',
    audioTrack: 'ஆடியோ ட்ராக்',
    reportIssue: 'சிக்கலைப் புகாரளிக்கவும்',
    addToPlaylist: 'பிளேலிஸ்ட்டில் சேர்',
    themeAppearance: 'தோற்றம்',
    chooseAppearance: 'தோற்றத்தைத் தேர்ந்தெடுக்கவும்',
    settingsTitle: 'அமைப்புகள்',
    language: 'மொழி',
    languageDesc: 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    selectLanguage: 'பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்',
    appearance: 'தோற்றம்',
    playback: 'பிளேபேக்',
    privacy: 'தனியுரிமை',
    plans: 'திட்டங்கள்',
    analytics: 'பகுப்பாய்வு',
    storage: 'சேமிப்பகம்',
    about: 'இன்பிளேயர் பற்றி',
    legalPolicies: 'சட்டக் கொள்கைகள்',
    termsOfService: 'சேவை விதிமுறைகள்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    childSafetyPolicy: 'குழந்தைகள் பாதுகாப்பு',
    communityGuidelines: 'சமூக வழிகாட்டுதல்கள்',
    loading: 'ஏற்றுகிறது...',
    noResults: 'முடிவுகள் எதுவும் இல்லை',
    errorOccurred: 'பிழை ஏற்பட்டது',
    offline: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்',
    success: 'வெற்றி',
  );

  static const telugu = AppStrings(
    code: 'te',
    home: 'హోమ్',
    shorts: 'రఫ్తార్ షార్ట్స్',
    music: 'సంగీతం',
    search: 'శోధించండి',
    library: 'లైబ్రరీ',
    profile: 'ప్రొఫైల్',
    settings: 'సెట్టింగ్‌లు',
    downloads: 'డౌన్‌లోడ్‌లు',
    notifications: 'నోటిఫికేషన్లు',
    messages: 'సందేశాలు',
    channels: 'ఛానెల్స్',
    creatorStudio: 'క్రియేటర్ స్టూడియో',
    mart: 'హామర్ట్',
    play: 'ప్లే చేయండి',
    pause: 'పాజ్ చేయండి',
    save: 'సేవ్ చేయండి',
    share: 'భాగస్వామ్యం చేయండి',
    like: 'ఇష్టం',
    dislike: 'అయిష్టం',
    subscribe: 'సబ్‌స్క్రయిబ్',
    subscribed: 'సబ్‌స్క్రయిబ్ చేయబడింది',
    cancel: 'రద్దు చేయండి',
    confirm: 'నిర్ధారించండి',
    apply: 'వర్తించు',
    edit: 'సవరించు',
    delete: 'తొలగించు',
    report: 'రిపోర్ట్ చేయండి',
    skip: 'దాటవేయి',
    close: 'మూసివేయి',
    signIn: 'సైన్ ఇన్',
    signOut: 'సైన్ అవుట్',
    back: 'వెనుకకు',
    done: 'పూర్తయింది',
    retry: 'మళ్ళీ ప్రయత్నించండి',
    quality: 'నాణ్యత',
    captions: 'ఉపశీర్షికలు',
    captionsOff: 'ఆఫ్',
    speed: 'ప్లేబ్యాక్ వేగం',
    audioTrack: 'ఆడియో ట్రాక్',
    reportIssue: 'సమస్యను నివేదించండి',
    addToPlaylist: 'ప్లేజాబితాకు జోడించండి',
    themeAppearance: 'రూపం',
    chooseAppearance: 'రూపాన్ని ఎంచుకోండి',
    settingsTitle: 'సెట్టింగ్‌లు',
    language: 'భాష',
    languageDesc: 'మీకు కావలసిన భాషను ఎంచుకోండి',
    selectLanguage: 'యాప్ భాషను ఎంచుకోండి',
    appearance: 'రూపం',
    playback: 'ప్లేబ్యాక్',
    privacy: 'గోప్యత',
    plans: 'ప్లాన్‌లు',
    analytics: 'విశ్లేషణలు',
    storage: 'నిల్వ',
    about: 'గురించి',
    legalPolicies: 'చట్టపరమైన విధానాలు',
    termsOfService: 'సేవా నిబంధనలు',
    privacyPolicy: 'గోప్యతా విధానం',
    childSafetyPolicy: 'పిల్లల భద్రతా విధానం',
    communityGuidelines: 'సంఘ మార్గదర్శకాలు',
    loading: 'లోడ్ అవుతోంది...',
    noResults: 'ఫలితాలు కనుగొనబడలేదు',
    errorOccurred: 'లోపం సంభవించింది',
    offline: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు',
    success: 'విజయవంతమైంది',
  );

  static const marathi = AppStrings(
    code: 'mr',
    home: 'होम',
    shorts: 'रफ्तार शॉर्ट्स',
    music: 'संगीत',
    search: 'शोधा',
    library: 'लाइब्ररी',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्ज',
    downloads: 'डाउनलोड्स',
    notifications: 'सूचना',
    messages: 'संदेश',
    channels: 'चॅनेल्स',
    creatorStudio: 'क्रिएटर स्टुडिओ',
    mart: 'हामार्ट',
    play: 'सुरू करा',
    pause: 'थांबवा',
    save: 'जतन करा',
    share: 'शेअर करा',
    like: 'पसंत',
    dislike: 'नापसंत',
    subscribe: 'सबस्क्राईब',
    subscribed: 'सबस्क्राईब केले',
    cancel: 'रद्द करा',
    confirm: 'पुष्टी करा',
    apply: 'लागू करा',
    edit: 'संपादित करा',
    delete: 'हटवा',
    report: 'तक्रार करा',
    skip: 'वगळा',
    close: 'बंद करा',
    signIn: 'साइन इन करा',
    signOut: 'साइन आउट करा',
    back: 'मागे',
    done: 'पूर्ण',
    retry: 'पुन्हा प्रयत्न करा',
    quality: 'गुणवत्ता',
    captions: 'उपशीर्षके',
    captionsOff: 'बंद',
    speed: 'गती',
    audioTrack: 'ऑडिओ ट्रॅक',
    reportIssue: 'समस्या कळवा',
    addToPlaylist: 'प्लेलिस्टमध्ये जोडा',
    themeAppearance: 'थीम आणि रूप',
    chooseAppearance: 'रूप निवडा',
    settingsTitle: 'सेटिंग्ज',
    language: 'भाषा',
    languageDesc: 'तुमची आवडती भाषा निवडा',
    selectLanguage: 'अ‍ॅप भाषा निवडा',
    appearance: 'रूप',
    playback: 'प्लेबॅक',
    privacy: 'खाते आणि गोपनीयता',
    plans: 'प्लॅन्स आणि खरेदी',
    analytics: 'अ‍ॅनालिटिक्स',
    storage: 'स्टोरेज',
    about: 'बद्दल',
    legalPolicies: 'कायदेशीर धोरणे',
    termsOfService: 'सेवा अटी',
    privacyPolicy: 'गोपनीयता धोरण',
    childSafetyPolicy: 'बाल सुरक्षा धोरण',
    communityGuidelines: 'समुदाय मार्गदर्शक तत्त्वे',
    loading: 'लोड होत आहे...',
    noResults: 'काहीही आढळले नाही',
    errorOccurred: 'त्रुटी आली',
    offline: 'तुम्ही ऑफलाइन आहात',
    success: 'यशस्वी',
  );

  static const gujarati = AppStrings(
    code: 'gu',
    home: 'હોમ',
    shorts: 'રફ્તાર શોર્ટ્સ',
    music: 'સંગીત',
    search: 'શોધો',
    library: 'લાઇબ્રેરી',
    profile: 'પ્રોફાઇલ',
    settings: 'સેટિંગ્સ',
    downloads: 'ડાઉનલોડ્સ',
    notifications: 'સૂચનાઓ',
    messages: 'સંદેશાઓ',
    channels: 'ચેનલો',
    creatorStudio: 'ક્રિએટર સ્ટુડિયો',
    mart: 'હામર્ટ',
    play: 'ચલાવો',
    pause: 'અટકાવો',
    save: 'સાચવો',
    share: 'શેર કરો',
    like: 'પસંદ',
    dislike: 'નાપસંદ',
    subscribe: 'સબ્સ્ક્રાઇબ',
    subscribed: 'સબ્સ્ક્રાઇબ કર્યું',
    cancel: 'રદ કરો',
    confirm: 'પુષ્ટિ કરો',
    apply: 'લાગુ કરો',
    edit: 'સંપાદિત કરો',
    delete: 'કાઢી નાખો',
    report: 'અહેવાલ આપો',
    skip: 'છોડો',
    close: 'બંધ કરો',
    signIn: 'સાઇન ઇન',
    signOut: 'સાઇન આઉટ',
    back: 'પાછા',
    done: 'સંપૂર્ણ',
    retry: 'ફરી પ્રયાસ કરો',
    quality: 'ગુણવત્તા',
    captions: 'ઉપશીર્ષકો',
    captionsOff: 'બંધ',
    speed: 'ઝડપ',
    audioTrack: 'ઓડિયો ટ્રેક',
    reportIssue: 'સમસ્યા જણાવો',
    addToPlaylist: 'પ્લેલિસ્ટમાં ઉમેરો',
    themeAppearance: 'દેખાવ',
    chooseAppearance: 'દેખાવ પસંદ કરો',
    settingsTitle: 'સેટિંગ્સ',
    language: 'ભાષા',
    languageDesc: 'તમારી પસંદગીની ભાષા પસંદ કરો',
    selectLanguage: 'ઍપની ભાષા પસંદ કરો',
    appearance: 'દેખાવ',
    playback: 'પ્લેબેક',
    privacy: 'ખાતું અને ગોપનીયતા',
    plans: 'પ્લાન',
    analytics: 'એનાલિટિક્સ',
    storage: 'સંગ્રહ',
    about: 'વિશે',
    legalPolicies: 'કાનૂની નીતિઓ',
    termsOfService: 'સેવાની શરતો',
    privacyPolicy: 'ગોપનીયતા નીતિ',
    childSafetyPolicy: 'બાળ સુરક્ષા નીતિ',
    communityGuidelines: 'સમુદાય માર્ગદર્શિકા',
    loading: 'લોડ થઈ રહ્યું છે...',
    noResults: 'કોઈ પરિણામ મળ્યું નથી',
    errorOccurred: 'ભૂલ આવી છે',
    offline: 'તમે ઑફલાઇન છો',
    success: 'સફળ',
  );

  static const kannada = AppStrings(
    code: 'kn',
    home: 'ಮುಖಪುಟ',
    shorts: 'ರಫ್ತಾರ್ ಶಾರ್ಟ್ಸ್',
    music: 'ಸಂಗೀತ',
    search: 'ಹುಡುಕಿ',
    library: 'ಲೈಬ್ರರಿ',
    profile: 'ಪ್ರೊಫೈಲ್',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    downloads: 'ಡೌನ್‌ಲೋಡ್‌ಗಳು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    messages: 'ಸಂದೇಶಗಳು',
    channels: 'ಚಾನಲ್‌ಗಳು',
    creatorStudio: 'ಕ್ರಿಯೇಟರ್ ಸ್ಟುಡಿಯೋ',
    mart: 'ಹಾಮರ್ಟ್',
    play: 'ಪ್ಲೇ ಮಾಡಿ',
    pause: 'ವಿರಾಮಗೊಳಿಸಿ',
    save: 'ಉಳಿಸಿ',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    like: 'ಇಷ್ಟ',
    dislike: 'ಇಷ್ಟವಿಲ್ಲ',
    subscribe: 'ಚಂದಾದಾರರಾಗಿ',
    subscribed: 'ಚಂದಾದಾರರಾಗಿದ್ದೀರಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    confirm: 'ದೃಢೀಕರಿಸಿ',
    apply: 'ಅನ್ವಯಿಸು',
    edit: 'ತಿದ್ದು',
    delete: 'ಅಳಿಸಿ',
    report: 'ವರದಿ ಮಾಡಿ',
    skip: 'ಬಿಟ್ಟುಬಿಡಿ',
    close: 'ಮುಚ್ಚಿ',
    signIn: 'ಸೈನ್ ಇನ್',
    signOut: 'ಸೈನ್ ಔಟ್',
    back: 'ಹಿಂದಕ್ಕೆ',
    done: 'ಮುಗಿದಿದೆ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    quality: 'ಗುಣಮಟ್ಟ',
    captions: 'ಉಪಶೀರ್ಷಿಕೆಗಳು',
    captionsOff: 'ಆಫ್',
    speed: 'ಪ್ಲೇಬ್ಯಾಕ್ ವೇಗ',
    audioTrack: 'ಆಡಿಯೋ ಟ್ರ್ಯಾಕ್',
    reportIssue: 'ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ',
    addToPlaylist: 'ಪ್ಲೇಪಟ್ಟಿ ಸೇರಿಸಿ',
    themeAppearance: 'ಗೋಚರತೆ',
    chooseAppearance: 'ಗೋಚರತೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    settingsTitle: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    language: 'ಭಾಷೆ',
    languageDesc: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    selectLanguage: 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    appearance: 'ಗೋಚರತೆ',
    playback: 'ಪ್ಲೇಬ್ಯಾಕ್',
    privacy: 'ಗೌಪ್ಯತೆ',
    plans: 'ಯೋಜನೆಗಳು',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    storage: 'ಸಂಗ್ರಹಣೆ',
    about: 'ಕುರಿತು',
    legalPolicies: 'ಕಾನೂನು ನೀತಿಗಳು',
    termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    childSafetyPolicy: 'ಮಕ್ಕಳ ಸುರಕ್ಷತೆ',
    communityGuidelines: 'ಸಮುದಾಯ ಮಾರ್ಗಸೂಚಿಗಳು',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    noResults: 'ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    errorOccurred: 'ದೋಷ ಸಂಭವಿಸಿದೆ',
    offline: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ',
    success: 'ಯಶಸ್ವಿಯಾಗಿದೆ',
  );

  static const malayalam = AppStrings(
    code: 'ml',
    home: 'ഹോം',
    shorts: 'റഫ്താർ ഷോർട്ട്സ്',
    music: 'സംഗീതം',
    search: 'തിരയുക',
    library: 'ലൈബ്രറി',
    profile: 'പ്രൊഫൈൽ',
    settings: 'ക്രമീകരണങ്ങൾ',
    downloads: 'ഡൗൺലോഡുകൾ',
    notifications: 'അറിയിപ്പുകൾ',
    messages: 'സന്ദേശങ്ങൾ',
    channels: 'ചാനലുകൾ',
    creatorStudio: 'ക്രിയേറ്റർ സ്റ്റുഡിയോ',
    mart: 'ഹാമാർട്ട്',
    play: 'പ്ലേ ചെയ്യുക',
    pause: 'താൽക്കാലികമായി നിർത്തുക',
    save: 'സംരക്ഷിക്കുക',
    share: 'പങ്കിടുക',
    like: 'ഇഷ്ടം',
    dislike: 'അനിഷ്ടം',
    subscribe: 'സബ്‌സ്‌ക്രൈബ്',
    subscribed: 'സബ്‌സ്‌ക്രൈബ് ചെയ്‌തു',
    cancel: 'റദ്ദാക്കുക',
    confirm: 'സ്ഥിരീകരിക്കുക',
    apply: 'ബാധകമാക്കുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    delete: 'ഇല്ലാതാക്കുക',
    report: 'റിപ്പോർട്ട് ചെയ്യുക',
    skip: 'ഒഴിവാക്കുക',
    close: 'അടയ്ക്കുക',
    signIn: 'സൈൻ ഇൻ',
    signOut: 'സൈൻ ഔട്ട്',
    back: 'പിന്നിലേക്ക്',
    done: 'പൂർത്തിയായി',
    retry: 'വീണ്ടും ശ്രമിക്കുക',
    quality: 'നിലവാരം',
    captions: 'സബ്‌ടൈറ്റിലുകൾ',
    captionsOff: 'ഓഫ്',
    speed: 'വേഗത',
    audioTrack: 'ഓഡിയോ ട്രാക്ക്',
    reportIssue: 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',
    addToPlaylist: 'പ്ലേലിസ്റ്റിലേക്ക് ചേർക്കുക',
    themeAppearance: 'രൂപഭാവം',
    chooseAppearance: 'രൂപഭാവം തിരഞ്ഞെടുക്കുക',
    settingsTitle: 'ക്രമീകരണങ്ങൾ',
    language: 'ഭാഷ',
    languageDesc: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    selectLanguage: 'ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക',
    appearance: 'രൂപഭാവം',
    playback: 'പ്ലേബാക്ക്',
    privacy: 'സ്വകാര്യത',
    plans: 'പ്ലാനുകൾ',
    analytics: 'അനലിറ്റിക്സ്',
    storage: 'സ്റ്റോറേജ്',
    about: 'കുറിച്ച്',
    legalPolicies: 'നിയമ നയങ്ങൾ',
    termsOfService: 'സേവന നിబంధനകൾ',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    childSafetyPolicy: 'കുട്ടികളുടെ സുരക്ഷ',
    communityGuidelines: 'കമ്മ്യൂണിറ്റി മാർഗ്ഗനിർദ്ദേശങ്ങൾ',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    noResults: 'ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
    errorOccurred: 'ഒരു പിശക് സംഭവിച്ചു',
    offline: 'നിങ്ങൾ ഓഫ്‌ലൈനിലാണ്',
    success: 'വിജയം',
  );

  static const punjabi = AppStrings(
    code: 'pa',
    home: 'ਹੋਮ',
    shorts: 'ਰਫ਼ਤਾਰ ਸ਼ਾਰਟਸ',
    music: 'ਸੰਗੀਤ',
    search: 'ਖੋਜੋ',
    library: 'ਲਾਇਬ੍ਰੇਰੀ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    downloads: 'ਡਾਊਨਲੋਡ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    messages: 'ਸੁਨੇਹੇ',
    channels: 'ਚੈਨਲ',
    creatorStudio: 'ਕ੍ਰਿਏਟਰ ਸਟੂਡੀਓ',
    mart: 'ਹਮਾਰਟ',
    play: 'ਚਲਾਓ',
    pause: 'ਰੋਕੋ',
    save: 'ਸੰਭਾਲੋ',
    share: 'ਸਾਂਝਾ ਕਰੋ',
    like: 'ਪਸੰਦ',
    dislike: 'ਨਾਪਸੰਦ',
    subscribe: 'ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ',
    subscribed: 'ਸਬਸਕ੍ਰਾਈਬ ਕੀਤਾ',
    cancel: 'ਰੱਦ ਕਰੋ',
    confirm: 'ਪੁਸ਼ਟੀ ਕਰੋ',
    apply: 'ਲਾਗੂ ਕਰੋ',
    edit: 'ਸੰਪਾਦਿਤ ਕਰੋ',
    delete: 'ਮਿਟਾਓ',
    report: 'ਰਿਪੋਰਟ ਕਰੋ',
    skip: 'ਛੱਡੋ',
    close: 'ਬੰਦ ਕਰੋ',
    signIn: 'ਸਾਈਨ ਇਨ',
    signOut: 'ਸਾਈਨ ਆਉਟ',
    back: 'ਪਿੱਛੇ',
    done: 'ਸੰਪੰਨ',
    retry: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    quality: 'ਗੁਣਵੱਤਾ',
    captions: 'ਸਬਟਾਈਟਲ',
    captionsOff: 'ਬੰਦ',
    speed: 'ਗਤੀ',
    audioTrack: 'ਆਡੀਓ ਟਰੈਕ',
    reportIssue: 'ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    addToPlaylist: 'ਪਲੇਲਿਸਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
    themeAppearance: 'ਦਿੱਖ',
    chooseAppearance: 'ਦਿੱਖ ਚੁਣੋ',
    settingsTitle: 'ਸੈਟਿੰਗਾਂ',
    language: 'ਭਾਸ਼ਾ',
    languageDesc: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
    selectLanguage: 'ਐਪ ਦੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    appearance: 'ਦਿੱਖ',
    playback: 'ਪਲੇਬੈਕ',
    privacy: 'ਗੋਪਨੀਯਤਾ',
    plans: 'ਪਲਾਨ',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    storage: 'ਸਟੋਰੇਜ',
    about: 'ਬਾਰੇ',
    legalPolicies: 'ਕਾਨੂੰਨੀ ਨੀਤੀਆਂ',
    termsOfService: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    privacyPolicy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
    childSafetyPolicy: 'ਬਾਲ ਸੁਰੱਖਿਆ ਨੀਤੀ',
    communityGuidelines: 'ਕਮਿਊਨਿਟੀ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    noResults: 'ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ',
    errorOccurred: 'ਕੋਈ ਤਰੁੱਟੀ ਆਈ ਹੈ',
    offline: 'ਤੁਸੀਂ ਔਫਲਾਈਨ ਹੋ',
    success: 'ਸਫਲਤਾ',
  );

  static const odia = AppStrings(
    code: 'or',
    home: 'ମୂଳପୃଷ୍ଠା',
    shorts: 'ରଫତାର ସର୍ଟ୍ସ',
    music: 'ସଙ୍ଗୀତ',
    search: 'ସନ୍ଧାନ',
    library: 'ଲାଇବ୍ରେରୀ',
    profile: 'ପ୍ରୋଫାଇଲ୍',
    settings: 'ସେଟିଙ୍ଗ୍ସ',
    downloads: 'ଡାଉନଲୋଡ୍',
    notifications: 'ବିଜ୍ଞପ୍ତି',
    messages: 'ବାର୍ତ୍ତା',
    channels: 'ଚ୍ୟାନେଲ୍',
    creatorStudio: 'କ୍ରିଏଟର ଷ୍ଟୁଡିଓ',
    mart: 'ହାମାର୍ଟ',
    play: 'ଚଲାନ୍ତୁ',
    pause: 'ରଖନ୍ତୁ',
    save: 'ସାଇତନ୍ତୁ',
    share: 'ସେୟାର କରନ୍ତୁ',
    like: 'ପସନ୍ଦ',
    dislike: 'ନାପସନ୍ଦ',
    subscribe: 'ସବସ୍କ୍ରାଇବ',
    subscribed: 'ସବସ୍କ୍ରାଇବ ହୋଇଛି',
    cancel: 'ବାତିଲ କରନ୍ତୁ',
    confirm: 'ନିଶ୍ଚିତ କରନ୍ତୁ',
    apply: 'ଲାଗୁ କରନ୍ତୁ',
    edit: 'ସମ୍ପାଦନା',
    delete: 'ହଟାନ୍ତୁ',
    report: 'ରିପୋର୍ଟ କରନ୍ତୁ',
    skip: 'ଛାଡ଼ନ୍ତୁ',
    close: 'ବନ୍ଦ କରନ୍ତୁ',
    signIn: 'ସାଇନ୍ ଇନ୍',
    signOut: 'ସାଇନ୍ ଆଉଟ୍',
    back: 'ପଛକୁ',
    done: 'ସମାପ୍ତ',
    retry: 'ପୁନଃଚେଷ୍ଟା',
    quality: 'ଗୁଣବତ୍ତା',
    captions: 'ସବ୍‌ଟାଇଟଲ୍',
    captionsOff: 'ବନ୍ଦ',
    speed: 'ଗତି',
    audioTrack: 'ଅଡିଓ ଟ୍ରାକ୍',
    reportIssue: 'ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ',
    addToPlaylist: 'ପ୍ଲେଲିଷ୍ଟରେ ଯୋଡ଼ନ୍ତୁ',
    themeAppearance: 'ରୂପରେଖ',
    chooseAppearance: 'ରୂପରେଖ ବାଛନ୍ତୁ',
    settingsTitle: 'ସେଟିଙ୍ଗ୍ସ',
    language: 'ଭାଷା',
    languageDesc: 'ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷା ବାଛନ୍ତୁ',
    selectLanguage: 'ଆପ୍ ଭାଷା ବାଛନ୍ତୁ',
    appearance: 'ରୂପରେଖ',
    playback: 'ପ୍ଲେବ୍ୟାକ୍',
    privacy: 'ଗୋପନୀୟତା',
    plans: 'ଯୋଜନା',
    analytics: 'ବିଶ୍ଳେଷଣ',
    storage: 'ସଂରକ୍ଷଣ',
    about: 'ବିଷୟରେ',
    legalPolicies: 'ଆଇନଗତ ନୀତି',
    termsOfService: 'ସେବା ସର୍ତ୍ତାବଳୀ',
    privacyPolicy: 'ଗୋପନୀୟତା ନୀତି',
    childSafetyPolicy: 'ଶିଶୁ ସୁରକ୍ଷା',
    communityGuidelines: 'ଗୋଷ୍ଠୀ ନିର୍ଦ୍ଦେଶାବଳୀ',
    loading: 'ଲୋଡ୍ ହେଉଛି...',
    noResults: 'କୌଣସି ଫଳାଫଳ ମିଳିଲା ନାହିଁ',
    errorOccurred: 'ତ୍ରୁଟି ଘଟିଲା',
    offline: 'ଆପଣ ଅଫଲାଇନ୍ ଅଛନ୍ତି',
    success: 'ସଫଳ',
  );

  static const assamese = AppStrings(
    code: 'as',
    home: 'গৃহপৃষ্ঠা',
    shorts: 'ৰফতাৰ শ্বৰ্টছ',
    music: 'সংগীত',
    search: 'সন্ধান',
    library: 'লাইব্ৰেৰী',
    profile: 'প্রফাইল',
    settings: 'ছেটিংছ',
    downloads: 'ডাউনল’ড',
    notifications: 'বিজ্ঞপ্তি',
    messages: 'বাৰ্তা',
    channels: 'চেনেলসমূহ',
    creatorStudio: 'ক্ৰিয়েটৰ ষ্টুডিঅ’',
    mart: 'হামাৰ্ট',
    play: 'প্লে কৰক',
    pause: 'ৰখাওক',
    save: 'সংৰক্ষণ',
    share: 'ভাগ-বতৰা',
    like: 'পছন্দ',
    dislike: 'অপছন্দ',
    subscribe: 'চাবস্ক্ৰাইব',
    subscribed: 'চাবস্ক্ৰাইব কৰা হ\'ল',
    cancel: 'বাতিল',
    confirm: 'নিশ্চিত কৰক',
    apply: 'প্ৰয়োগ কৰক',
    edit: 'সম্পাদনা',
    delete: 'মচি পেলাওক',
    report: 'অভিযোগ',
    skip: 'এৰাই যাওক',
    close: 'বন্ধ কৰক',
    signIn: 'ছাইন ইন',
    signOut: 'ছাইন আউট',
    back: 'উভতি যাওক',
    done: 'সম্পন্ন',
    retry: 'পুনৰ চেষ্টা কৰক',
    quality: 'গুণগত মান',
    captions: 'উপশীৰ্ষক',
    captionsOff: 'বন্ধ',
    speed: 'গতি',
    audioTrack: 'অডিঅ\' ট্ৰেক',
    reportIssue: 'সমস্যা প্ৰতিবেদন কৰক',
    addToPlaylist: 'প্লেলিষ্টত যোগ কৰক',
    themeAppearance: 'ৰূপ',
    chooseAppearance: 'ৰূপ বাছনি কৰক',
    settingsTitle: 'ছেটিংছ',
    language: 'ভাষা',
    languageDesc: 'আপোনাৰ পছন্দৰ ভাষা বাছনি কৰক',
    selectLanguage: 'এপৰ ভাষা বাছনি কৰক',
    appearance: 'ৰূপ',
    playback: 'প্লেবেক',
    privacy: 'গোপনীয়তা',
    plans: 'পৰিকল্পনা',
    analytics: 'বিশ্লেষণ',
    storage: 'ষ্ট\'ৰেজ',
    about: 'বিষয়ে',
    legalPolicies: 'আইনী নীতি',
    termsOfService: 'সেৱাৰ চৰ্তাৱলী',
    privacyPolicy: 'গোপনীয়তা নীতি',
    childSafetyPolicy: 'শিশু সুৰক্ষা',
    communityGuidelines: 'সম্প্ৰদায়ৰ নিৰ্দেশনাৱলী',
    loading: 'ল\'ড হৈ আছে...',
    noResults: 'কোনো ফলাফল পোৱা নগ\'ল',
    errorOccurred: 'এটা আসোঁৱাহ ঘটিছে',
    offline: 'আপুনি অফলাইনত আছে',
    success: 'সফল',
  );

  static const Map<String, AppStrings> _all = {
    'en': english,
    'hi': hindi,
    'bn': bengali,
    'ta': tamil,
    'te': telugu,
    'mr': marathi,
    'gu': gujarati,
    'kn': kannada,
    'ml': malayalam,
    'pa': punjabi,
    'or': odia,
    'as': assamese,
  };

  /// Returns localized AppStrings for given language code with fallback to English.
  static AppStrings get(String? langCode) {
    if (langCode == null) return english;
    final normalized = langCode.toLowerCase().split('_')[0].split('-')[0];
    return _all[normalized] ?? english;
  }
}
