import '../legal_policies_data.dart';

const LegalPolicyDoc childSafetyPolicy = LegalPolicyDoc(
  id: 'child-safety',
  title: 'Child Safety Policy',
  effectiveDate: 'September 5, 2026',
  version: '2026-09-05',
  externalUrl: 'https://inplayer.in/child-safety',
  preamble: r'''Platform: InPlayer
Operated By: HOMOX PRIME PRIVATE LIMITED
Office Address: 6th Floor, 615, Shivanta Highstreet, Panchavati Canal Road, Near Shivanta Iris, Gorwa, Vadodara, Gujarat – 390016, India
GSTIN: 24AAICH1282J1ZK
Website: www.inplayer.in
Support: support@inplayer.in
General Email: homoxprimepvtltd@gmail.com

InPlayer is committed to providing a safe digital environment for children and users of all age groups.

This Child Safety Policy explains how InPlayer seeks to protect children from sexual exploitation, grooming, inappropriate content, harassment, abuse, harmful interactions and other online risks.

This Policy forms part of the InPlayer Terms & Conditions, Privacy Policy and Community Guidelines.''',
  sections: [
    LegalPolicySection(
      id: 'purpose',
      title: '1. PURPOSE',
      content: r'''InPlayer is committed to providing a safe digital environment for children and users of all age groups.

InPlayer is an India-focused video and creator platform operated by:
HOMOX PRIME PRIVATE LIMITED
6th Floor, 615, Shivanta Highstreet, Panchavati Canal Road, Near Shivanta Iris, Gorwa, Vadodara, Gujarat – 390016, India

This Child Safety Policy explains how InPlayer seeks to protect children from sexual exploitation, grooming, inappropriate content, harassment, abuse, harmful interactions and other online risks.

This Policy forms part of the InPlayer Terms & Conditions, Privacy Policy and Community Guidelines.''',
    ),
    LegalPolicySection(
      id: 'who-is-child',
      title: '2. WHO IS A CHILD?',
      content: r'''For purposes of this Policy, a child means a person below 18 years of age, consistent with the applicable Indian intermediary framework.

InPlayer may use age-related information and technical age-estimation mechanisms to determine an approximate age category for safety and content-recommendation purposes.

Age estimation is not a legal identity verification system and may not always accurately determine a person's actual age.''',
    ),
    LegalPolicySection(
      id: 'all-age-platform',
      title: '3. INPLAYER IS AN ALL-AGE PLATFORM',
      content: r'''InPlayer is designed as an all-age platform.

The Platform is intended to provide age-appropriate experiences to users while maintaining strict safeguards against content or conduct that could harm children.

Creators are responsible for ensuring that their content complies with InPlayer's Community Guidelines and Child Safety Policy.''',
    ),
    LegalPolicySection(
      id: 'zero-tolerance',
      title: '4. ZERO TOLERANCE FOR CHILD SEXUAL EXPLOITATION',
      content: r'''InPlayer has zero tolerance for:

• child sexual abuse;
• child sexual exploitation;
• child sexual abuse material (CSAM);
• sexualisation of children;
• sexual solicitation of children;
• grooming;
• sexual extortion of children;
• trafficking or exploitation of children;
• commercial sexual exploitation of children;
• requests for sexual images from children;
• sharing sexual material involving children;
• arranging sexual contact with children; or
• any other conduct that sexually exploits or endangers a child.

Such conduct may result in immediate account termination and reporting to competent authorities where required by applicable law.''',
    ),
    LegalPolicySection(
      id: 'prohibited-content',
      title: '5. PROHIBITED CHILD SEXUAL CONTENT',
      content: r'''Users must never upload, share, request, create, generate, distribute or promote content that sexually exploits or sexualises a child.

This includes:

• photographs;
• videos;
• livestreams;
• AI-generated content;
• digitally manipulated content;
• deepfakes;
• drawings or animations where prohibited by applicable law;
• audio;
• messages;
• links;
• advertisements; and
• any other material used to sexually exploit children.

A claim that content was generated by AI or is fictional does not make otherwise unlawful child sexual exploitation acceptable.''',
    ),
    LegalPolicySection(
      id: 'grooming',
      title: '6. GROOMING',
      content: r'''InPlayer prohibits grooming of children.

Grooming may include behaviour intended to build trust with a child for the purpose of:

• sexual exploitation;
• obtaining sexual images;
• arranging inappropriate meetings;
• sexual conversations;
• coercion;
• manipulation;
• blackmail;
• trafficking; or
• other exploitation.

Users must not use InPlayer's comments, chat, livestreams, profiles or other features to groom children.''',
    ),
    LegalPolicySection(
      id: 'sexual-solicitation',
      title: '7. SEXUAL SOLICITATION OF MINORS',
      content: r'''Users must not:

• ask children for sexual photographs;
• request sexual videos;
• request sexual conversations;
• ask children to move to another platform for sexual purposes;
• offer money or gifts in exchange for sexual material;
• threaten children into providing sexual material; or
• attempt to arrange sexual contact with a child.

Such conduct may result in immediate suspension or permanent termination.''',
    ),
    LegalPolicySection(
      id: 'non-consensual-content',
      title: '8. NON-CONSENSUAL OR EXPLOITATIVE CONTENT',
      content: r'''InPlayer prohibits content involving:

• sexual exploitation of minors;
• intimate material involving minors;
• non-consensual intimate imagery;
• sexual blackmail;
• sextortion;
• threats involving private images;
• exploitation of children for commercial purposes.

Users should report such material immediately rather than downloading, copying or redistributing it.''',
    ),
    LegalPolicySection(
      id: 'adult-sexual-content',
      title: '9. ADULT SEXUAL CONTENT',
      content: r'''InPlayer is an all-age platform and explicit pornography and explicit adult sexual content are prohibited.

Users must not upload or distribute:

• pornography;
• explicit sexual acts;
• explicit sexual videos;
• sexual exploitation;
• explicit sexual solicitation;
• explicit sexual services advertisements; or
• sexually explicit content involving minors.

Age estimation is not intended to make prohibited pornography acceptable.

Adult age classification does not override InPlayer's prohibition on explicit sexual content.''',
    ),
    LegalPolicySection(
      id: 'age-estimation',
      title: '10. AGE ESTIMATION AND CHILD SAFETY',
      content: r'''InPlayer may use face-based age-estimation technology to help determine an approximate age category.

The purpose is to help the Platform provide a safer and more age-appropriate experience.

For example:

• a child may receive child-appropriate recommendations;
• a teenager may receive age-appropriate content;
• an adult may receive content intended for adults where such content is otherwise permitted by InPlayer policy.

The system is intended as a safety mechanism and is not guaranteed to be completely accurate.

Users must not attempt to manipulate, deceive or bypass the age-estimation system.''',
    ),
    LegalPolicySection(
      id: 'face-scan-privacy',
      title: '11. FACE-SCAN PRIVACY',
      content: r'''The face scan is intended for age-estimation and safety purposes.

InPlayer's stated design is not to maintain a permanent facial-recognition database from the age-estimation scan.

The face image/video used for age estimation is intended not to be permanently retained after the relevant age-estimation process is completed, subject to the technical processing performed by the relevant third-party technology provider.

The handling of any personal information associated with age estimation is governed by the InPlayer Privacy Policy and applicable Indian data-protection requirements.''',
    ),
    LegalPolicySection(
      id: 'third-party-tech',
      title: '12. THIRD-PARTY AGE-ESTIMATION TECHNOLOGY',
      content: r'''InPlayer may use third-party technology, including technology provided by Google or another service provider, to assist with age estimation.

Such providers may process technical information necessary to provide the age-estimation service.

InPlayer will seek to use such services in accordance with applicable law and applicable contractual/privacy requirements.

Users should also review applicable third-party privacy information where relevant.''',
    ),
    LegalPolicySection(
      id: 'age-suitable-content',
      title: '13. AGE-SUITABLE CONTENT',
      content: r'''Creators must consider the likely age of their audience when publishing content.

Creators must not deliberately design:

• thumbnails;
• titles;
• descriptions;
• tags;
• advertisements; or
• promotional material

to attract children to content that is inappropriate or prohibited for children.

InPlayer may restrict, remove, age-classify or reduce distribution of content where appropriate.''',
    ),
    LegalPolicySection(
      id: 'children-comments',
      title: '14. CHILDREN AND COMMENTS',
      content: r'''Comments must remain safe and respectful.

Users must not use comments to:

• sexually solicit children;
• groom children;
• threaten children;
• bully children;
• request private contact information;
• request sexual images;
• encourage children to meet strangers;
• manipulate children into leaving the Platform for exploitative purposes; or
• otherwise endanger a child.

InPlayer may remove comments and restrict users who violate these rules.''',
    ),
    LegalPolicySection(
      id: 'children-chat',
      title: '15. CHILDREN AND CHAT',
      content: r'''Where chat or messaging features are available, users must comply with strict child-safety requirements.

Users must not use chat to:

• sexually contact children;
• groom children;
• request sexual material;
• threaten or blackmail children;
• arrange exploitative meetings;
• send inappropriate sexual material to children;
• encourage children to hide conversations from parents/guardians for exploitative purposes.

InPlayer may restrict, suspend or disable communication features when necessary for safety.''',
    ),
    LegalPolicySection(
      id: 'private-communication',
      title: '16. PRIVATE COMMUNICATION',
      content: r'''Users should not ask children to provide unnecessary personal information.

This may include:

• home address;
• school address;
• private phone number;
• passwords;
• financial information;
• precise location;
• identity documents;
• private photographs; or
• other sensitive information.

Users must not use personal information to harass, threaten, exploit or manipulate children.''',
    ),
    LegalPolicySection(
      id: 'child-harassment-bullying',
      title: '17. CHILD HARASSMENT AND BULLYING',
      content: r'''InPlayer prohibits:

• cyberbullying;
• threats;
• targeted harassment;
• humiliation;
• repeated abuse;
• intimidation;
• blackmail;
• stalking;
• coordinated harassment of children.

Where appropriate, InPlayer may remove content, restrict accounts or disable relevant communication features.''',
    ),
    LegalPolicySection(
      id: 'commercial-exploitation',
      title: '18. CHILD EXPLOITATION FOR COMMERCIAL PURPOSES',
      content: r'''Users must not exploit children for financial or commercial gain.

This includes:

• sexual exploitation;
• fraudulent fundraising involving children;
• deceptive commercial activity targeting children;
• inappropriate sponsorship targeting children;
• exploiting children to generate engagement;
• using children in prohibited advertising;
• manipulating children into purchasing products.''',
    ),
    LegalPolicySection(
      id: 'children-monetization',
      title: '19. CHILDREN AND MONETIZATION',
      content: r'''Creators are responsible for ensuring that monetized content complies with applicable laws and InPlayer policies.

Where a child is involved in monetized content, creators must ensure that:

• the content is lawful;
• the child is not exploited;
• the child is not sexually exploited;
• the child is not used in prohibited commercial activity;
• applicable permissions/consents are obtained where required; and
• the content does not violate child-safety standards.

InPlayer may restrict monetization where child-safety concerns exist.''',
    ),
    LegalPolicySection(
      id: 'children-sponsorships',
      title: '20. CHILDREN AND SPONSORSHIPS',
      content: r'''Sponsored content involving or directed toward children must be created responsibly.

Creators must not:

• sexually exploit children in sponsored content;
• deceive children about commercial relationships;
• encourage children to engage in dangerous activities;
• promote prohibited products to children;
• manipulate children into purchases;
• conceal required commercial disclosures.

InPlayer may remove or restrict sponsorship content that violates applicable law or Platform policy.''',
    ),
    LegalPolicySection(
      id: 'children-shop',
      title: '21. CHILDREN AND SHOP FEATURES',
      content: r'''Creators and sellers must not use InPlayer's shop functionality to exploit children.

Users must not:

• market prohibited products to children;
• deceive children about prices or products;
• request unnecessary personal information from children;
• encourage unsafe purchases;
• use children for fraudulent transactions.

Where transactions involve minors, applicable consumer-protection and legal requirements must be followed.''',
    ),
    LegalPolicySection(
      id: 'dangerous-challenges',
      title: '22. DANGEROUS CHALLENGES INVOLVING CHILDREN',
      content: r'''Content encouraging children to participate in dangerous activities may be removed.

Examples include:

• dangerous physical challenges;
• serious injury challenges;
• dangerous consumption challenges;
• weapons-related challenges;
• activities involving serious risk of injury;
• criminal challenges.

Educational or safety-focused discussions may be permitted when they do not encourage participation.''',
    ),
    LegalPolicySection(
      id: 'self-harm-suicide',
      title: '23. CHILD SELF-HARM AND SUICIDE CONTENT',
      content: r'''Users must not encourage or instruct children to:

• commit suicide;
• seriously self-harm;
• participate in dangerous self-harm challenges; or
• harm another person.

Awareness, educational and recovery-related content may be permitted when it does not encourage harmful behaviour.''',
    ),
    LegalPolicySection(
      id: 'drugs-children',
      title: '24. DRUGS AND CHILDREN',
      content: r'''Users must not encourage children to:

• purchase illegal drugs;
• consume illegal drugs;
• participate in drug distribution;
• experiment with dangerous substances;
• participate in dangerous substance challenges.

Content that educates users about the risks of drugs may be permitted.''',
    ),
    LegalPolicySection(
      id: 'weapons-children',
      title: '25. WEAPONS AND CHILDREN',
      content: r'''Users must not encourage children to unlawfully acquire, use or misuse weapons.

Content involving weapons for legitimate:

• news;
• educational;
• historical;
• documentary; or
• fictional entertainment

purposes may be allowed where consistent with InPlayer's Community Guidelines.''',
    ),
    LegalPolicySection(
      id: 'child-privacy',
      title: '26. CHILD PRIVACY',
      content: r'''InPlayer recognises that children's personal information requires additional care.

InPlayer may collect and process information necessary to:

• provide the Platform;
• maintain account security;
• provide age-appropriate services;
• protect children;
• prevent abuse;
• comply with law; and
• provide requested features.

InPlayer will handle applicable personal data according to its Privacy Policy and the applicable Indian data-protection framework.''',
    ),
    LegalPolicySection(
      id: 'child-consent',
      title: '27. CHILD DATA AND CONSENT',
      content: r'''Where applicable law requires additional consent, verification or safeguards for processing a child's personal data, InPlayer will implement the applicable requirements.

InPlayer may use reasonable technical measures to help determine age and apply appropriate safeguards.

The exact implementation may depend on the Platform's technical architecture and applicable law.''',
    ),
    LegalPolicySection(
      id: 'parent-guardian-role',
      title: '28. PARENT AND GUARDIAN ROLE',
      content: r'''Parents and lawful guardians are encouraged to:

• supervise children's use of online services;
• discuss online safety;
• use available family controls;
• review content access;
• report suspicious behaviour;
• report exploitation or abuse;
• ensure children do not share unnecessary personal information.

Parents/guardians may contact InPlayer regarding child-safety concerns.''',
    ),
    LegalPolicySection(
      id: 'in-family',
      title: '29. IN-FAMILY',
      content: r'''InPlayer may provide the In-Family feature to support family-related functionality.

Depending on the features available, In-Family may assist with:

• family account relationships;
• age-appropriate content;
• family safety;
• parental controls;
• content preferences;
• child-safety settings.

Features may change over time.''',
    ),
    LegalPolicySection(
      id: 'reporting-concerns',
      title: '30. REPORTING CHILD-SAFETY CONCERNS',
      content: r'''If you believe a child is being:

• sexually exploited;
• groomed;
• threatened;
• harassed;
• blackmailed;
• exposed to prohibited sexual content;
• targeted by an adult for exploitation; or
• otherwise placed at serious risk,

you should report the matter immediately through InPlayer's reporting mechanism.

Users should not redistribute suspected illegal child sexual content.''',
    ),
    LegalPolicySection(
      id: 'report-button',
      title: '31. REPORT BUTTON',
      content: r'''InPlayer may provide a Report function.

Users may report:

• Child Safety;
• Sexual/Adult Content;
• Grooming;
• Harassment;
• Threats;
• Privacy violation;
• Illegal content;
• Scam/Fraud;
• Copyright;
• Other safety concerns.

Users should provide sufficient information to help InPlayer investigate.''',
    ),
    LegalPolicySection(
      id: 'emergency-safety',
      title: '32. EMERGENCY AND SERIOUS SAFETY MATTERS',
      content: r'''Where a report indicates an immediate or serious risk to a child, InPlayer may take urgent protective action.

Depending on the circumstances and applicable law, this may include:

• removing or restricting content;
• disabling an account;
• restricting communications;
• preserving relevant information;
• escalating internally;
• contacting competent authorities; and
• taking other legally appropriate measures.''',
    ),
    LegalPolicySection(
      id: 'reporting-competent-authorities',
      title: '33. REPORTING TO COMPETENT AUTHORITIES',
      content: r'''Where required or permitted by applicable law, InPlayer may report serious child-safety violations to appropriate governmental, law-enforcement or child-protection authorities.

This may include suspected:

• child sexual exploitation;
• CSAM;
• trafficking;
• serious threats;
• sexual solicitation of minors;
• serious criminal conduct.''',
    ),
    LegalPolicySection(
      id: 'moderation-tech',
      title: '34. MODERATION TECHNOLOGY',
      content: r'''InPlayer may use:

• automated moderation;
• AI-based detection;
• age-classification systems;
• image/video analysis;
• human moderators;
• user reports;
• account signals;
• safety systems

to identify potential child-safety violations.

Automated systems may not always be perfect.

InPlayer may use human review where appropriate.''',
    ),
    LegalPolicySection(
      id: 'content-removal',
      title: '35. CONTENT REMOVAL',
      content: r'''InPlayer may remove or restrict content where it reasonably believes the content:

• violates this Policy;
• harms children;
• sexually exploits children;
• violates the Community Guidelines;
• violates applicable law;
• creates a serious child-safety risk.

Serious child-safety violations may result in immediate removal without a prior warning.''',
    ),
    LegalPolicySection(
      id: 'account-enforcement',
      title: '36. ACCOUNT ENFORCEMENT',
      content: r'''Depending on the seriousness of the violation, InPlayer may take one or more of the following actions:

Warning → Content Removal → Demonetization → Feature Restriction → Temporary Suspension → Permanent Termination

For severe child-safety violations, InPlayer may skip progressive enforcement and immediately suspend or permanently terminate the account.''',
    ),
    LegalPolicySection(
      id: 'creator-responsibility-child',
      title: '37. CREATOR RESPONSIBILITY',
      content: r'''Creators must take reasonable steps to ensure that their content does not:

• sexually exploit children;
• encourage child exploitation;
• expose children to prohibited content;
• facilitate grooming;
• encourage dangerous conduct;
• reveal children's private information;
• encourage children to engage in unsafe interactions.

Creators are responsible for content uploaded to their channels.''',
    ),
    LegalPolicySection(
      id: 'children-appearance',
      title: '38. CHILDREN\'S APPEARANCE IN CONTENT',
      content: r'''The appearance of a child in lawful content does not itself violate this Policy.

However, creators must ensure that:

• the child is not sexually exploited;
• the child is not presented in a sexually explicit manner;
• the content does not expose the child to unreasonable danger;
• privacy and applicable permissions are respected;
• the content does not violate any applicable law.

InPlayer may restrict content where child welfare concerns arise.''',
    ),
    LegalPolicySection(
      id: 'ai-deepfakes-child',
      title: '39. AI, DEEPFAKES AND CHILD SAFETY',
      content: r'''AI-generated or digitally altered content involving children must comply with these Guidelines and applicable law.

Strictly prohibited conduct includes:

• sexual deepfakes involving minors;
• synthetic sexual images of minors;
• AI-generated CSAM;
• sexualisation of children through AI;
• deceptive exploitation of a child's identity;
• AI-assisted grooming or exploitation.

Claims that such content is “AI-generated,” “fake” or “fictional” do not automatically make prohibited child sexual exploitation acceptable.''',
    ),
    LegalPolicySection(
      id: 'child-safety-by-design',
      title: '40. CHILD-SAFETY BY DESIGN',
      content: r'''InPlayer may consider child safety when developing:

• recommendations;
• search;
• comments;
• chat;
• livestreaming;
• notifications;
• advertising;
• sponsorship;
• shopping;
• creator monetization;
• age classification.

Safety controls may be strengthened or modified as technology and legal requirements develop.''',
    ),
    LegalPolicySection(
      id: 'advertising-children',
      title: '41. ADVERTISING TO CHILDREN',
      content: r'''Advertising and promotional activity involving children must comply with applicable Indian law and InPlayer's advertising policies.

InPlayer may restrict certain advertising categories for child-directed audiences.

Prohibited or inappropriate advertising may be removed.''',
    ),
    LegalPolicySection(
      id: 'data-security',
      title: '42. DATA SECURITY',
      content: r'''InPlayer will take reasonable technical and organisational measures to protect personal information.

Additional safeguards may be applied where appropriate to information relating to children.

Users should not share sensitive information through public comments or chats.''',
    ),
    LegalPolicySection(
      id: 'privacy-policy-link',
      title: '43. PRIVACY POLICY',
      content: r'''The collection and processing of personal information, including age-related information and information associated with age-estimation systems, is governed by the InPlayer Privacy Policy.

Users and parents/guardians should read the Privacy Policy for detailed information about:

• data collection;
• age estimation;
• data retention;
• deletion;
• third-party providers;
• user rights;
• grievances.''',
    ),
    LegalPolicySection(
      id: 'appeals',
      title: '44. APPEALS',
      content: r'''Where content or an account is restricted or removed, the affected creator/user may use the applicable InPlayer appeal process where available.

An appeal may be appropriate where:

• content was removed incorrectly;
• age classification was incorrect;
• an account was incorrectly restricted;
• a child-safety report was incorrectly interpreted.

Serious safety action may remain in effect during review where necessary to protect users.''',
    ),
    LegalPolicySection(
      id: 'false-reporting',
      title: '45. FALSE REPORTING',
      content: r'''Users must not knowingly submit false child-safety reports to:

• harass creators;
• remove competitors' content;
• damage another user's account;
• manipulate Platform moderation.

Abuse of the reporting system may result in enforcement.

Good-faith reports will not be penalised merely because the reported content is ultimately found not to violate the Policy.''',
    ),
    LegalPolicySection(
      id: 'no-retaliation',
      title: '46. NO RETALIATION',
      content: r'''InPlayer does not permit retaliation against a person who makes a good-faith child-safety report.

Users must not:

• threaten reporters;
• reveal their identity to harass them;
• intimidate reporters;
• organise harassment against reporters.''',
    ),
    LegalPolicySection(
      id: 'repeat-violations',
      title: '47. REPEAT CHILD-SAFETY VIOLATIONS',
      content: r'''Repeated violations may result in stronger action, including:

• permanent demonetization;
• loss of creator privileges;
• loss of chat functionality;
• loss of livestream access;
• channel suspension;
• account termination.''',
    ),
    LegalPolicySection(
      id: 'serious-violations',
      title: '48. SERIOUS VIOLATIONS',
      content: r'''InPlayer may permanently terminate an account immediately for serious violations such as:

• CSAM;
• child sexual exploitation;
• grooming;
• sexual solicitation of minors;
• trafficking;
• sexual blackmail of minors;
• deliberate creation/distribution of child sexual exploitation material;
• repeated serious child-safety violations.''',
    ),
    LegalPolicySection(
      id: 'legal-compliance',
      title: '49. LEGAL COMPLIANCE',
      content: r'''This Policy operates alongside applicable Indian laws and regulations, including applicable information-technology, intermediary, privacy, child-protection, criminal and consumer-protection requirements.

The Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, as updated, contain intermediary obligations concerning harmful-to-child content and related due diligence.

India's current data-protection framework also includes the Digital Personal Data Protection Rules, 2025 and related implementation materials published by MeitY.

Where mandatory law imposes a stricter requirement than this Policy, the mandatory legal requirement will prevail.''',
    ),
    LegalPolicySection(
      id: 'cooperation-authorities',
      title: '50. COOPERATION WITH AUTHORITIES',
      content: r'''InPlayer may cooperate with competent authorities in matters involving serious child-safety concerns where required or permitted by applicable law.

This may include lawful requests concerning:

• child exploitation;
• trafficking;
• grooming;
• serious threats;
• cybercrime;
• unlawful content;
• other serious offences.''',
    ),
    LegalPolicySection(
      id: 'updates-policy',
      title: '51. UPDATES TO THIS POLICY',
      content: r'''InPlayer may update this Child Safety Policy from time to time to reflect:

• changes in law;
• regulatory requirements;
• new safety risks;
• new Platform features;
• new moderation technology;
• child-safety best practices.

The latest version will be made available through the InPlayer Platform or website.''',
    ),
    LegalPolicySection(
      id: 'grievance-officer',
      title: '52. GRIEVANCE OFFICER',
      content: r'''For child-safety complaints and grievances:

Grievance Officer: Mr. Ramchandra Kushwaha
Email: support@inplayer.in
Company: Homox Prime Private Limited
Address:
6th Floor, 615, Shivanta Highstreet, Panchavati Canal Road, Near Shivanta Iris, Gorwa, Vadodara, Gujarat – 390016, India''',
    ),
    LegalPolicySection(
      id: 'child-safety-contact',
      title: '53. CHILD SAFETY CONTACT',
      content: r'''For urgent child-safety concerns, users should use:

InPlayer Report function
or
Email: support@inplayer.in

The report should contain enough information to identify the relevant account, channel, content or interaction.

Users should not attach or redistribute suspected illegal child sexual material unless specifically required through a lawful reporting process.''',
    ),
    LegalPolicySection(
      id: 'our-commitment',
      title: '54. OUR COMMITMENT',
      content: r'''InPlayer is committed to maintaining a platform where:

• Children are protected.
• Creators are responsible.
• Users are treated with respect.
• Illegal exploitation is not tolerated.
• Safety comes before engagement or revenue.

InPlayer may continuously improve its child-safety systems as the Platform grows.

END OF CHILD SAFETY POLICY
HOMOX PRIME PRIVATE LIMITED
INPLAYER''',
    ),
  ],
);
