import { NextRequest, NextResponse } from "next/server";
import { GetCommand, UpdateCommand, DeleteCommand } from "@aws-sdk/lib-dynamodb";
import { docClient } from "@/app/lib/dynamodb";
import { verifyAuth } from "@/app/lib/verifyAuth";
import mux from "@/app/lib/mux";
import { THUMBNAIL_DATA_URL_MAX_LENGTH } from "@/app/lib/imageCompress";

const VISIBILITY_VALUES = ["public", "unlisted", "private"];
const SPOKEN_LANGUAGE_VALUES = ["auto", "en", "hi", "bn"];

interface Params {
  params: Promise<{ videoId: string }>;
}

async function verifyOwnership(videoId: string, userId: string) {
  const result = await docClient.send(
    new GetCommand({ TableName: "InPlayer-Videos", Key: { videoId } })
  );

  if (!result.Item) {
    return { error: "Video not found.", status: 404 } as const;
  }

  if (result.Item.uploaderId !== userId) {
    return { error: "You don't own this video.", status: 403 } as const;
  }

  return { video: result.Item } as const;
}

export async function PATCH(request: NextRequest, { params }: Params) {
  let user;

  try {
    user = await verifyAuth(request);
  } catch {
    return NextResponse.json({ error: "Please sign in." }, { status: 401 });
  }

  const { videoId } = await params;
  const ownership = await verifyOwnership(videoId, user.userId);

  if ("error" in ownership) {
    return NextResponse.json({ error: ownership.error }, { status: ownership.status });
  }

  const body = await request.json();
  const {
    title,
    description,
    category,
    tags,
    visibility,
    madeForKids,
    ageRestricted,
    commentsEnabled,
    spokenLanguage,
    thumbnailDataUrl,
    thumbnailUrl,
  } = body;

  if (!title?.trim() || !category?.trim()) {
    return NextResponse.json(
      { error: "Title and category are required." },
      { status: 400 }
    );
  }

  if (visibility !== undefined && !VISIBILITY_VALUES.includes(visibility)) {
    return NextResponse.json({ error: "Invalid visibility." }, { status: 400 });
  }

  if (
    thumbnailDataUrl !== undefined &&
    thumbnailDataUrl !== null &&
    thumbnailDataUrl !== "" &&
    (typeof thumbnailDataUrl !== "string" ||
      !thumbnailDataUrl.startsWith("data:image/") ||
      thumbnailDataUrl.length > THUMBNAIL_DATA_URL_MAX_LENGTH)
  ) {
    return NextResponse.json(
      { error: "That thumbnail image is too large or invalid. Please try a different image." },
      { status: 400 }
    );
  }

  // Same field set the Upload page collects, so the edit panel can offer
  // true parity (see app/components/VideoMetadataFields.tsx, shared by
  // both). contentType is deliberately never accepted here — changing it
  // after upload would desync the static-rendition/captions pipeline,
  // which is keyed off the value chosen at creation time.
  const sets: string[] = [
    "title = :title",
    "description = :description",
    "category = :category",
  ];
  const values: Record<string, unknown> = {
    ":title": title.trim(),
    ":description": description?.trim() || "",
    ":category": category.trim(),
  };

  if (Array.isArray(tags)) {
    sets.push("tags = :tags");
    values[":tags"] = tags
      .filter((t: unknown) => typeof t === "string" && t.trim())
      .slice(0, 15)
      .map((t: string) => t.trim());
  }
  if (visibility !== undefined) {
    sets.push("visibility = :visibility");
    values[":visibility"] = visibility;
  }
  if (madeForKids !== undefined) {
    sets.push("madeForKids = :madeForKids");
    values[":madeForKids"] = !!madeForKids;
  }
  if (ageRestricted !== undefined) {
    sets.push("ageRestricted = :ageRestricted");
    values[":ageRestricted"] = !!ageRestricted;
  }
  if (commentsEnabled !== undefined) {
    sets.push("commentsEnabled = :commentsEnabled");
    values[":commentsEnabled"] = !!commentsEnabled;
  }
  if (spokenLanguage !== undefined && SPOKEN_LANGUAGE_VALUES.includes(spokenLanguage)) {
    sets.push("spokenLanguage = :spokenLanguage");
    values[":spokenLanguage"] = spokenLanguage;
  }
  if (
    typeof thumbnailDataUrl === "string" &&
    thumbnailDataUrl.startsWith("data:image/")
  ) {
    sets.push("customThumbnailUrl = :thumb", "thumbnailUrl = :thumb");
    values[":thumb"] = thumbnailDataUrl;
  } else if (
    typeof thumbnailUrl === "string" &&
    thumbnailUrl.startsWith("https://image.mux.com/")
  ) {
    // Creator selected a frame generated by Mux.
    sets.push("thumbnailUrl = :thumb");
    values[":thumb"] = thumbnailUrl;
  }

  await docClient.send(
    new UpdateCommand({
      TableName: "InPlayer-Videos",
      Key: { videoId },
      UpdateExpression: `SET ${sets.join(", ")}`,
      ExpressionAttributeValues: values,
    })
  );

  return NextResponse.json({ success: true });
}

export async function DELETE(request: NextRequest, { params }: Params) {
  let user;

  try {
    user = await verifyAuth(request);
  } catch {
    return NextResponse.json({ error: "Please sign in." }, { status: 401 });
  }

  const { videoId } = await params;
  const ownership = await verifyOwnership(videoId, user.userId);

  if ("error" in ownership) {
    return NextResponse.json({ error: ownership.error }, { status: ownership.status });
  }

  // Also delete the underlying Mux asset, so storage isn't kept (and
  // billed) for a video that no longer exists in the app.
  if (ownership.video.muxAssetId) {
    try {
      await mux.video.assets.delete(ownership.video.muxAssetId);
    } catch (err) {
      console.error("Failed to delete Mux asset (continuing anyway):", err);
    }
  }

  await docClient.send(
    new DeleteCommand({ TableName: "InPlayer-Videos", Key: { videoId } })
  );

  return NextResponse.json({ success: true });
}